### ISSUE TITLE
County-wise counts of tests and cases discrepancy 

### ISSUE THREAD

**Issue by ParamjitGill** [dkahle/texas-covid#6]
Hi David,
Thank you for sharing the covid data.  I am looking at the two excel spreadsheets displaying the number of tests and cases in Texas counties by days.  The Tests data starts on April 21. So, under the column "Tests Through April 21" would mean the number of covid tests conducted in the given county up to April 21. Right? In the case counts spreadsheet the column "Cases04-21" would display the number of covid cases in a given county up to April 21. Right?  However, for county Andrews, for example, we see the number of tests equal to 2, whereas the number of cases reported is equal to 19.  How can the number of cases be more than the number of tests?  Can you please explain this discrepancy? 
Thank you,
Paramjit

**Comment by dkahle** [comment]
Hi @ParamjitGill, I think your interpretation of tests and cases is right. I don't have an answer to your question. My understanding is that the test and case reports don't necessarily correspond, and the way I interpret that is that case reports may lag tests. Obviously, your example shows the opposite, so what's going on there? I really don't know, I assume that the reporting is just imperfect. 

In the beginning those problems consumed me and I couldn't get anywhere. Why the lag? What's the distribution of the lag? The test methods aren't uniform, so what's the distribution of tests by types? (That remains a very important question, actually.) In general aggregating over time would seem to alleviate any lag time questions, although obviously at the cost of temporal resolution (thus things like 2wk positivity rate). But that just seems to be the cost of doing anything, because that's the data we have. I think we have to assume that the data is by and large reliable for what is claims to be, especially for the past few months. But there are all sorts of issues there for sure, and epis are going to be writing papers on this stuff for decades.

**Comment by ParamjitGill** [comment]
Hi David,
Thank you for the reply. There seems to be no description of the data collection methodology.  At this point, we can say that data on the number of tests as reported can't be combined with the number of cases in a given county, even after mussing over a week. Typically, number of tests conducted is used as a denominator to compute the "rate".  Of course, the county population size will serve that purpose.
Paramjit
________________________________

**Comment by dkahle** [comment]
Hi @ParamjitGill, I don't think anyone would disagree with the problems in the data, but there what we've got, they're what we're given. Of course the cases _can_ be combined with tests, the question is whether the result provides anything useful. Clearly it does: it provides a crude estimate of the positivity rate on the date provided. The longer the aggregation, the more likely the window contains a greater proportion of cases-to-tests, so the estimate becomes more stable in the apples-to-apples sense (and also in the statistical sense, but again assumptions would be brought there). And that's what I meant by relying on the data to be that which they are claimed to be. Dividing by the population gives a rate, for sure, but it's a different rate, and with it you can't entertain questions such as "Is the spread becoming worse?"  because there is a major mediating factor: tests. So, I totally a agree that the tests are problematic and the results have to be understood with a grain of salt, but I don't think we can just say that they contain no information whatsoever.
